version: "3.5"
services:
  web:
    build: .
    ports: 
      - "80:80"
    restart: always
    depends_on:
      - db
    links: 
      - db
    

  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: NoviNano